package io.unipayment.sdk.model.enums;

public enum TransactionType {
    DEPOSIT, DEPOSITPAYMENT, PAYMENTFEE, FEEADJUSTMENT, ADJUSTMENTSWAP, SWAPINVOICE, INVOICEREFUND, REFUND, SWAP, PAYMENT, ADJUSTMENT
}
